### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by rc14193** [marcelkalveram/react-native-bulletproof-redux-provider#3]
I'm setting up a new app. I have the dependencies installed, but I'm getting the following error

`[Unhandled promise rejection: Error: TypeError: null is not an object (evaluating 'RNKeychainManager.getGenericPasswordForOptions')]
at node_modules/react-native-bulletproof-redux-provider/src/store/encryption/getEncryptionKey.js:36:10 in getEncryptionKey
at node_modules/react-native-bulletproof-redux-provider/src/store/encryption/getEncryptionKey.js:11:54 in getEncryptionKey
at node_modules/react-native-bulletproof-redux-provider/src/components/EncryptionGate.js:25:51 in <anonymous>
at node_modules/react-native-bulletproof-redux-provider/src/components/EncryptionGate.js:24:5 in <anonymous>
at node_modules/react-native-bulletproof-redux-provider/src/components/EncryptionGate.js:24:4 in useEffect$argument_0
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:54:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:4 in runApplication
`
nodejs v14.17.5
npm v6.14.14

  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.7",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-bulletproof-redux-provider": "^1.0.3",
    "react-native-keychain": "^7.0.0",
    "react-native-securerandom": "^1.0.0",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.4",
    "redux": "^4.1.1"
  },

**Comment by rc14193** [comment]
For anyone who may stumble across this in the future, this was because I was using expo go for my development. This library needs to use native modules that don't work with expo go. If you want to continue using expo you will have to [setup a custom dev client](https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8?gi=f97c48b9a471).
